EXPERIMENT_NAME: experiment_003
ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 1000000
FINAL_GREEDY_EPSILON_EPOCH: 100000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 100000
BATCH_SIZE: 256
DUP_FREQ: 10000
GAMMA: 0.9
LR: 0.001

MIN_CART_POSITION: -4.8
MAX_CART_POSITION: 4.8
MIN_CART_VELOCITY: -10.0
MAX_CART_VELOCITY: 10.0
MIN_CART_POLE_ANGLE: -0.42
MAX_CART_POLE_ANGLE: 0.42
MIN_CART_POLE_VELOCITY: -10.0
MAX_CART_POLE_VELOCITY: 10.0
REWARD_REWARD_SUCCESS: 10
REWARD_PENALTY_FAIL: -10
FRAME_SKIP: 2
ACTIONS: [0, 1]
