ACTION_SPACE_SEED: 42
RANDOM_SEED: 42
ACTIONS: [0, 1]
SCORING_WINDOW_SIZE: 100

TRAINING_EPOCHS: 150000
FINAL_GREEDY_EPSILON_EPOCH: 0.5
FINAL_GREEDY_EPSILON: 0.01
BUFFER_SIZE: 0.5
BATCH_SIZE: 64
DUP_FREQ: 50
GAMMA: 0.95
LR: 0.0005
DROPOUT_P: 0.5
ARCHITECTURE: [4, 64, 32, 2]
FRAME_SKIP: 3
