ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 10000
FINAL_GREEDY_EPSILON_EPOCH: 7000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 1000
BATCH_SIZE: 64
DUP_FREQ: 1000
GAMMA: 0.9
LR: 0.001

MAX_CART_POSITION: 4.8
CLIP_CART_VELOCITY: 10.0
MAX_CART_POLE_ANGLE: 0.2095
MAX_CART_POLE_VELOCITY: 10.0
MAX_REWARD: 500
REWARD_PENALTY_FAIL: -10
FRAME_SKIP: 3

ACTIONS: [0, 1]
