EXPERIMENT_NAME: experiment_003
ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 100000
FINAL_GREEDY_EPSILON_EPOCH: 10000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 100000
BATCH_SIZE: 32
DUP_FREQ: 1000
GAMMA: 0.9
LR: 0.001

MIN_CART_POSITION: -4.8
MAX_CART_POSITION: 4.8
MIN_CART_VELOCITY: -40.0
MAX_CART_VELOCITY: 40.0
MIN_CART_POLE_ANGLE: -4.2
MAX_CART_POLE_ANGLE: 4.2
MIN_CART_POLE_ANGULAR_VELOCITY: -50.0
MAX_CART_POLE_ANGULAR_VELOCITY: 50.0
REWARD_REWARD_SUCCESS: 10
REWARD_PENALTY_FAIL: -10
FRAME_SKIP: 2
ACTIONS: [0, 1]
