ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 100000
FINAL_GREEDY_EPSILON_EPOCH: 25000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 100000
BATCH_SIZE: 128
DUP_FREQ: 250
GAMMA: 0.99
LR: 0.00025
DROPOUT_P: 0.0
ARCHITECTURE: [4, 32, 16, 2]

FRAME_SKIP: 1
ACTIONS: [0, 1]
