EXPERIMENT_NAME: experiment_009
ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 100000
FINAL_GREEDY_EPSILON_EPOCH: 50000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 100000
BATCH_SIZE: 128
DUP_FREQ: 1000
GAMMA: 0.99
LR: 0.001

MIN_CART_POSITION: -2.4
MAX_CART_POSITION: 2.4
MIN_CART_VELOCITY: -2.0
MAX_CART_VELOCITY: 2.0
MIN_CART_POLE_ANGLE: -0.2095
MAX_CART_POLE_ANGLE: 0.2095
MIN_CART_POLE_ANGULAR_VELOCITY: -2.0
MAX_CART_POLE_ANGULAR_VELOCITY: 2.0
REWARD_REWARD_SUCCESS: 3
REWARD_PENALTY_FAIL: -3
FRAME_SKIP: 1
ACTIONS: [0, 1]
