ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 100
BUFFER_SIZE: 1000
BATCH_SIZE: 32
DUP_FREQ: 2000
GAMMA: 0.9
LR: 0.001

MAX_CART_POSITION: 4.8
CLIP_CART_VELOCITY: 10.0
MAX_CART_POLE_ANGLE: 0.2095
MAX_CART_POLE_VELOCITY: 10.0

ACTIONS: [0, 1]
