EXPERIMENT_NAME: experiment_009
ACTION_SPACE_SEED: 42
RANDOM_SEED: 42

TRAINING_EPOCHS: 100000
FINAL_GREEDY_EPSILON_EPOCH: 10000
FINAL_GREEDY_EPSILON: 0.05
BUFFER_SIZE: 50000
BATCH_SIZE: 64
DUP_FREQ: 1000
GAMMA: 0.99
LR: 0.00025

FRAME_SKIP: 1
ACTIONS: [0, 1]
